
# ===================================
# Development Configuration
# ===================================

server:
  port: 8081

spring:

  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

    # JPA Configuration
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        stat: DEBUG

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# AWS Configuration (for development - using localstack or test credentials)
cloud:
  aws:
    region: eu-central-1
    credentials:
      access-key: access-key
      secret-key: secret-key

    s3:
      bucket: food-stack-file-storage

#  JWT Configuration
app:
  jwt:
    secret: secret
    expiration: 86400000 # 24 hours