spring:
  application:
    name: fs
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: crate-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        stat: DEBUG

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: XXXXXXXXXX
      secret-key: YYYYYYYYYY
    region: eu-central-1
    s3:
      bucket: food-stack-file-storage
      region: eu-central-1