spring:
  application:
    name: fs
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      access-key: XXXXXXXXXX
      secret-key: YYYYYYYYYY
    region: eu-central-1
    s3:
      bucket: food-stack-file-storage